DROP TABLE IF EXISTS anomaly_evidence;
DROP TABLE IF EXISTS anomalies;
DROP TABLE IF EXISTS analyses;
DROP TABLE IF EXISTS events;
DROP TABLE IF EXISTS readings;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS meters;
